[modengine]
debug = true

external_dlls = ["external_dll/*.dll"]

# Mod loader configuration
[extension.mod_loader]
enabled = true

# Not currently supported for Elden Ring
loose_params = false

mods = [
    { enabled = true, name = "sero", path = "." }
]

[extension.scylla_hide]
enabled = false